# Exported from Render on 2024-06-08T07:44:26Z
services:
- type: web
  name: MernChatApp
  runtime: node
  repo: https://github.com/Sourabh7singh/MernChatApp
  plan: free
  envVars:
  - key: MongoUri
    sync: false
  - key: PORT
    sync: false
  region: singapore
  buildCommand: 'npm install; '
  startCommand: node index.js;
  healthCheckPath: /
  rootDir: Backend
version: "1"
